import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Components",
  description: "Generated by create next app",
  authors: [
    { name: "Deemanth Poonacha", url: "https://github.com/DeemanthPoonacha" },
  ],
};

export default function ContentLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <h2>title</h2>
      {children}
    </>
  );
}
