import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Components",
  description: "Generated by create next app",
  authors: [
    { name: "Deemanth Poonacha", url: "https://github.com/DeemanthPoonacha" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col min-h-screen w-full ">
          <Header />
          <div className="w-full min-h-[90vh] flex flex-col align-middle justify-center items-stretch px-24 m-auto dark:border-gray-800 light:border-gray-100 border-2">
            {children}
          </div>
          <div className="">footer</div>
        </main>
      </body>
    </html>
  );
}
